### ISSUE TITLE
openssh 8.8p1 have problem

### ISSUE THREAD

**Issue by spacexnasa** [SoftwareAG/ganymed-ssh-2#2]
hello, we met a problem,we upgrade our openssh server to 8.8p1,then display this error message 

java.io.IOException: There was a problem while connecting to 192.168.110.171:22
ch.ethz.ssh2.Connection.connect(Connection.java:699)
com.tianque.datagroup.dataplatform.odps.util.LinuxSshUtil.callShellCommand(LinuxSshUtil.java:70)
com.tianque.datagroup.dataplatform.odps.taskflowengine.work.impl.ShellWorkNodeAction.execute(ShellWorkNodeAction.java:81)
com.tianque.datagroup.dataplatform.odps.taskflowengine.work.impl.AbstractWorkNodeAction.doAction(AbstractWorkNodeAction.java:86)
com.tianque.datagroup.dataplatform.odps.taskflowengine.service.impl.CodeWorkNodeServiceImpl.lambda$executeDebugAndGenerateLog$54(CodeWorkNodeServiceImpl.java:182)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

        at com.tianque.datagroup.dataplatform.odps.util.LinuxSshUtil.callShellCommand(LinuxSshUtil.java:93)
        at com.tianque.datagroup.dataplatform.odps.taskflowengine.work.impl.ShellWorkNodeAction.execute(ShellWorkNodeAction.java:81)
        ... 5 more
Caused by: java.io.IOException: There was a problem while connecting to 192.168.110.171:22
        at ch.ethz.ssh2.Connection.connect(Connection.java:699)
        at com.tianque.datagroup.dataplatform.odps.util.LinuxSshUtil.callShellCommand(LinuxSshUtil.java:70)
        ... 6 more
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
        at ch.ethz.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:91)
        at ch.ethz.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:229)
        at ch.ethz.ssh2.Connection.connect(Connection.java:655)
        ... 7 more
Caused by: java.io.IOException: Cannot negotiate, proposals do not match.
        at ch.ethz.ssh2.transport.KexManager.handleMessage(KexManager.java:412)
        at ch.ethz.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:753)
        at ch.ethz.ssh2.transport.TransportManager$1.run(TransportManager.java:468)
        ... 1 more

no matching host key type found. Their offer: ssh-rsa 
 i checked the openssh website (https://www.openssh.com/legacy.html)
and change the config file,still can not work. hope check and fix.

many thanks.

**Comment by spacexnasa** [comment]
KexAlgorithms diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group1-sha1,curve25519-sha256@libssh.org
